### ISSUE TITLE
Refactor with `@nrwl/devkit`

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#129] opened 2021-03-22 10:04 UTC
This task will simplify the code a lot, but it's a lot of work.

**Comment by RicardoJBarrios** [comment] 2021-06-20 08:40
I think that #206 is a duplicate of this. 

I've been diving in the code and needs a rewrite of a big part of the code, but I think is needed to be framework agnostic and multiple ci friendly.

**Comment by edbzn** [comment] 2021-06-20 09:26
@RicardoJBarrios agree with that, also we think that using Promises would be enough for semver, migrating to @nrwl/devkit could be the good time to refactor using Promises

**Closed** 2021-09-07 09:17 UTC
Labels: enhancement
