### ISSUE TITLE
Calculating wrong version number

### ISSUE THREAD

**Issue by dgonzalezr** [jscutlery/semver#762] opened 2023-12-22 06:09 UTC
Hi,

I wanted to trigger a new release on our Nx monorepo yesterday, but whenever I run:

```
npx nx run workspace:version
```

is not picking or calculating the right version, is not taking into account the last version (current v0.10.0) and is calculating for the release v0.9.0 😒 and no change is seen.

[Our Nx monorepo](https://github.com/Endava/BEEQ) release in sync mode, we have been using this plugin in all our releases without issue. The git tags are set correctly and can also be listed in the CLI.

We are kinda block now and we have a bunch of new features that we would like to release as soon as possible. Any help is really appreciated 🙌🏼.

**Comment by edbzn** [comment] 2023-12-22 08:11
Hey @dgonzalezr, I found out that the issue is due to the custom preset usage. I'm still investigating concretely why but to unlock your release without waiting for a fix you could use the base preset, instead of: 

```json
"preset": {
  "name": "conventionalcommits",
  "types": [
    { "type": "feat", "section": "Features ⚡️" },
    { "type": "fix", "section": "Bug Fixes 🐞" },
    { "type": "test", "section": "Test 🧪" },
    { "type": "docs", "section": "Documentation 📚" },
    { "type": "style", "section": "Style 🎨" },
    { "type": "chore", "section": "Chore ⚙️" },
    { "type": "perf", "section": "Performance ⌛️" },
    { "type": "refactor", "hidden": true },
    { "type": "release", "hidden": true }
  ]
}
``` 

use `"preset": "conventionalcommits`, it will work again.

**Comment by edbzn** [comment] 2023-12-22 09:52
It's fixed in https://github.com/jscutlery/semver/releases/tag/semver-4.2.0, thank you!

**Closed by edbzn** 2023-12-22 09:52 UTC
Labels: bug
