### ISSUE TITLE
NoVerify builder option (or command flag) works only when doing git push.

### ISSUE THREAD

**Issue by nicolashzmor** [jscutlery/semver#216] opened 2021-06-15 13:46 UTC
I've started using your library a few days ago and I found a use case that you may haven't considered.

I'm not sure if it's a good or bad practice, but I have my local testing pipeline (lint, test, etc) on my pre-commit hook. 

I followed the path of the options that we defined on the architect target definition, and it seems that the only place where you explicitly use the noVerify option is in [here: ](https://github.com/jscutlery/semver/blob/main/packages/semver/src/builders/version/builder.ts), line 77.

My condition is: I've put the ``` affected --target=version --no-verify``` command into another hook, after the pre-commit. 
My issue is: when the command makes the version changes commit, it runs my pre-commit hook again, disregarding the noVerify option.

I'm not sure if this is a designed behaviour or just a strange use case.

Please, let me know if I can be of any help.

**Comment by edbzn** [comment] 2021-06-15 14:08
I think the affected command does not forward arguments to the specified target, so semver uses the default value defined in the schema. Have you tried to define the option in the `angular.json` or `workspace.json` instead of using CLI argument?

```json
  "version": {
          "builder": "@jscutlery/semver:version",
          "options": {
            "noVerify": true
          }
   }
```

**Comment by edbzn** [comment] 2021-06-15 14:22
The `noVerify` option is merged with common options between sync & independent mode and used by `standard-version` here:
 https://github.com/jscutlery/semver/blob/76ad8837cdb0b36ab8d51c2f856ff2db8080abb7/packages/semver/src/builders/version/version.ts#L124

**Comment by nicolas-hernandezamor** [comment] 2021-06-15 14:26
Hello @edbzn, thanks for your reply.

Yes, I've tried both ways of configuring the noVerify.. same result.
`
"version": {
  "builder": "@jscutlery/semver:version",
  "options": {
    "syncVersions": false,
    "noVerify": true
  }
},
`

**Comment by edbzn** [comment] 2021-06-15 14:31
Mmh, seems to be a bug. Does it work when simply running `nx version <project>` or is it related to the affected command?

**Comment by nicolas-hernandezamor** [comment] 2021-06-15 14:35
Just a setup to reproduce:

```
"version": {
  "builder": "@jscutlery/semver:version",
  "options": {
    "syncVersions": false,
    "noVerify": true
  }
},
```

```
#! /bin/bash  ## pre-commit
yarn affected:lint
yarn affected:test
yarn affected:build
```

Case 1: Post Commit. Gets into an infinite loop of committing library tags
Case 2: Pre Push: Runs the Pre Commit Hook again
```
#! /bin/bash ## post-commit | pre-push
nx affected --target=version --no-verify ## tested with flag and with builder option
```

**Comment by nicolas-hernandezamor** [comment] 2021-06-15 14:36
> Mmh, seems to be a bug. Does it work when simply running `nx version <project>` or is it related to the affected command?

Same behavior

**Comment by edbzn** [comment] 2021-09-28 20:39
@gabsmprocha @nicolashernandezamor-drd It's weird because the underlying package that creates the commit gets the `noVerify` option correctly. I need to investigate further, but I'm currently working on something else, I'm not against another hand for fixing this.

**Comment by edbzn** [comment] 2021-11-28 13:33
Hi, finally fixed this. Thanks for reporting!

**Closed by edbzn** 2021-11-28 13:33 UTC
Labels: bug
