### ISSUE TITLE
package.json of the libs is not updated 

### ISSUE THREAD

**Issue by petergrau** [jscutlery/semver#65] opened 2021-02-01 14:50 UTC
I am not sure if it is a bug or feature. When running:

`nx run workspace:version`

the changelog of the libs is udpated but no version bump is happening for the `package.json` in that lib. 

```
    "workspace": {
      "architect": {
        "version": {
          "builder": "@jscutlery/semver:version",
          "options": {
            "syncVersions": true
          }
        }
      },
      "root": "."
    }
```

**Comment by edbzn** [comment] 2021-02-01 15:21
I'm not able to reproduce this, in my sandbox repo package.json files get correctly updated when releasing in sync mode. Could you provide more context?

**Comment by petergrau** [comment] 2021-02-01 15:25
Just when trying to reproduce the issue once more it worked. Not sure what was different this time but I think the issue can be closed for now.

**Comment by petergrau** [comment] 2021-02-01 15:40
Sorry for re-opening. I just did a `git reset` and tried again and ran into the same issue again. The script just stops during the "create changelog" process without any error:

```
[...]
✔ outputting changes to /worksapce/libs[placeholder]/CHANGELOG.md
✔ outputting changes to /worksapce/apps/[placeholder]/CHANGELOG.md
✔ outputting changes to /worksapce/libs[placeholder]/CHANGELOG.md
✔ outputting changes to /worksapce/libs/[placeholder]/CHANGELOG.md
✔ outputting changes to /worksapce/libs/[placeholder]/CHANGELOG.md

>  NX   CLOUD  See run details at https://nx.app/runs/[placeholder]

```

Is there any option for verbose output? (I did try to disable nx cloud but did not change the result.)

Actually when I ran the same command twice more it finishes without an error.

**Comment by edbzn** [comment] 2021-02-01 16:05
I'm suspecting Nx Cloud to interfere but I will try to reproduce your scenario to be sure.

**Comment by petergrau** [comment] 2021-02-25 10:16
@edbzn where you able to reproduce the bug?

**Comment by edbzn** [comment] 2022-05-02 15:31
I'm going to close this, feel free to reopen if this is not resolved.

**Closed by edbzn** 2022-05-02 15:31 UTC
Labels: bug
