### ISSUE TITLE
Unable to use Plugin 

### ISSUE THREAD

**Issue by Temi89** [jscutlery/semver#90] opened 2021-02-22 09:53 UTC
Hi there I have tried to use this plug and added the following to my config asper documentation . 

   "version": {
          "builder": "@jscutlery/semver:version",
          "options": {
            "push": true,
            "remote": "origin",
            "baseBranch": "origin/master"
          }
        }

all I get is the following is logged with nothing happening :  nx run my-ap:version --dry-run  .  No package update or logs

**Comment by edbzn** [comment] 2021-02-22 11:08
Hi, the `"baseBranch"` option should be the branch name to push against and not the concatenation *origin* + *branch*, but that's not the problem if nothing is versioned. 

Your commit history should contain fix, feature or breaking change since last release to version your package. Is it the case? Is it the first time you version your library? If not, what is the last git tag?

It's hard to see what's wrong without the context, could you provide more informations or a reproduction?

Thank you.

**Comment by edbzn** [comment] 2021-02-22 11:19
@Temi89 I just released a fix (1.3.2)  to not fail silently, if you rerun the version command it should help us to understand what's wrong.

**Comment by Temi89** [comment] 2021-02-22 11:42
> @Temi89 I just released a fix (1.3.2) to not fail silently, if you rerun the version command it should help us to understand what's wrong.

Finally got some errors coming out of this now. something to do with my path anydieas ?  

Error: fatal: unrecognized argument: --path=apps/frontend

![Screenshot 2021-02-22 at 11 36 35](https://user-images.githubusercontent.com/18047134/108703728-ea868180-7502-11eb-844f-eef31ea8304f.png)
![Screenshot 2021-02-22 at 11 40 32](https://user-images.githubusercontent.com/18047134/108703735-ec504500-7502-11eb-820a-86aa653a47da.png)

**Comment by Temi89** [comment] 2021-02-22 11:49
> Hi, the `"baseBranch"` option should be the branch name to push against and not the concatenation _origin_ + _branch_, but that's not the problem if nothing is versioned.
> 
> Your commit history should contain fix, feature or breaking change since last release to version your package. Is it the case? Is it the first time you version your library? If not, what is the last git tag?
> 
> It's hard to see what's wrong without the context, could you provide more informations or a reproduction?
> 
> Thank you.

So for the commit I am following the structure you mentioned above something like fix(sales1): add new item to basket. It wouldn't be the first time previously was running semantic release from the root and the current tag is on v1.3.0 . Also was expecting the dry run to update  my package version just to understand its behaviour before pushing it to gitlab .

**Comment by edbzn** [comment] 2021-02-22 13:21
>  It wouldn't be the first time previously was running semantic release from the root and the current tag is on v1.3.0.

With independent mode, in order to avoid tag conflicts between projects semver assumes the previous tag to be formatted as `project-x.x.x`, in your case it should be `frontend-1.3.0`. If the tag is not found it should raise an error related to Git revision, which is not your case. :thinking:  Just to be sure, could you try to retag with the suffix as mentioned and rerun `nx run frontend:version --dry-run`. 

If it does not fix I will try to reproduce on my side.

> Also was expecting the dry run to update my package version just to understand its behaviour before pushing it to gitlab.

In dry mode the filesystem is not impacted, it just logs the result in the console. If you want to see your package.json updated you can disable the `--push` option to test locally, do not forget to remove the created tag / commits after your tests.

**Comment by Temi89** [comment] 2021-02-23 06:52
> > It wouldn't be the first time previously was running semantic release from the root and the current tag is on v1.3.0.
> 
> With independent mode, in order to avoid tag conflicts between projects semver assumes the previous tag to be formatted as `project-x.x.x`, in your case it should be `frontend-1.3.0`. If the tag is not found it should raise an error related to Git revision, which is not your case. 🤔 Just to be sure, could you try to retag with the suffix as mentioned and rerun `nx run frontend:version --dry-run`.
> 
> If it does not fix I will try to reproduce on my side.
> 
> > Also was expecting the dry run to update my package version just to understand its behaviour before pushing it to gitlab.
> 
> In dry mode the filesystem is not impacted, it just logs the result in the console. If you want to see your package.json updated you can disable the `--push` option to test locally, do not forget to remove the created tag / commits after your tests.

HI Thanks for coming back to me . Indeed I did try to get the error when tags dont exist and I do get an error relative to the tag not found as soon as I create the tag I still end up with the same error about my path not recognised. 
![Screenshot 2021-02-23 at 06 44 17](https://user-images.githubusercontent.com/18047134/108810418-00e41a00-75a3-11eb-9967-835b3dbccef5.png)
![Screenshot 2021-02-23 at 06 44 25](https://user-images.githubusercontent.com/18047134/108810421-03467400-75a3-11eb-800c-dad58ea06978.png)

**Comment by edbzn** [comment] 2021-03-01 11:30
I don't understand why this option `--path=apps/frontend` is passed because the package we use `git-raw-commits` should format it as the following git valid option `-- apps/frontend` ([see this](https://github.com/conventional-changelog/conventional-changelog/blob/8076d4666c2a3ea728b95bf1e4e78d4c7189b1dc/packages/git-raw-commits/index.js#L35)).

I checked if the package fixed something since the last version (2.0.10 and we use the 2.0.0), but nothing related to this.

**Comment by edbzn** [comment] 2022-05-02 15:31
I'm going to close this, feel free to reopen if this is not resolved.

**Closed by edbzn** 2022-05-02 15:31 UTC
Labels: bug
